### ISSUE TITLE
Missing event time in resulted events

### ISSUE THREAD

**Issue by HHansi** [kevalmorabia97/SEDTWik-Event-Detection-from-Tweets#1]
Hi,
Thank you for your interesting findings and this repository.

I executed the main.py file using the sample data you provided and it generated some .txt files as the results. Each of these .txt files contains a list of text segments, newsworthiness value and some segments related to each extracted segment. I believe each .txt file describes a single event. But, there is no any detail about the event occurred time written in result files. 

According to the results shown in Table 1 and Table 4 of the paper (SEDTWik: Segmentation-based event detection from tweets using Wikipedia), both event information and date (event occurred time) was identified using SEDTWik. Is there any missing section in this repository or do I have to change some configuration to get event times? Or does your solution only result the events in the inserted file without identifying the subwindows they occurred?

**Comment by kevalmorabia97** [comment]
Hi @HHansi, the model was run one by one for all the days that's why we know what date it occurred. Our current model is not able to find when exactly an event occurred but you still get to know within which time window it occurred
